//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diascan.Agent.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diascan.Agent.Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Aspose_Total {
            get {
                object obj = ResourceManager.GetObject("Aspose_Total", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\.
        /// </summary>
        internal static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon_16x16 {
            get {
                object obj = ResourceManager.GetObject("favicon_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        internal static string FileExtensionJson {
            get {
                return ResourceManager.GetString("FileExtensionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .log.
        /// </summary>
        internal static string FileExtensionLog {
            get {
                return ResourceManager.GetString("FileExtensionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryDataModel.db.
        /// </summary>
        internal static string NameDirectoryDataBaseFile {
            get {
                return ResourceManager.GetString("NameDirectoryDataBaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в течении последней минуты перед началом движения.
        /// </summary>
        internal static string NavLastMinuteSetupPhase {
            get {
                return ResourceManager.GetString("NavLastMinuteSetupPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перед началом движения.
        /// </summary>
        internal static string NavSetupPhase {
            get {
                return ResourceManager.GetString("NavSetupPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to во время движения.
        /// </summary>
        internal static string NavWorkPhase {
            get {
                return ResourceManager.GetString("NavWorkPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акселерометры БИНС в норме.
        /// </summary>
        internal static string NormalAccelerometer {
            get {
                return ResourceManager.GetString("NormalAccelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гироскопы БИНС в норме.
        /// </summary>
        internal static string NormalGyroscope {
            get {
                return ResourceManager.GetString("NormalGyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гироскопы и/или акселерометры БИНС в норме.
        /// </summary>
        internal static string NormalGyroscopeAndOrAccelerometer {
            get {
                return ResourceManager.GetString("NormalGyroscopeAndOrAccelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гироскопы или акселерометры БИНС в норме.
        /// </summary>
        internal static string NormalGyroscopeOrAccelerometer {
            get {
                return ResourceManager.GetString("NormalGyroscopeOrAccelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в течении 600 секунд перед началом движения.
        /// </summary>
        internal static string SetupPhaseLast600Sec {
            get {
                return ResourceManager.GetString("SetupPhaseLast600Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMP.
        /// </summary>
        internal static string TEMP {
            get {
                return ResourceManager.GetString("TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акселерометры БИНС не в норме.
        /// </summary>
        internal static string WrongAccelerometer {
            get {
                return ResourceManager.GetString("WrongAccelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гироскопы БИНС не в норме.
        /// </summary>
        internal static string WrongGyroscope {
            get {
                return ResourceManager.GetString("WrongGyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гироскопы и/или акселерометры БИНС не в норме.
        /// </summary>
        internal static string WrongGyroscopeAndOrAccelerometer {
            get {
                return ResourceManager.GetString("WrongGyroscopeAndOrAccelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гироскопы или акселерометры БИНС не в норме.
        /// </summary>
        internal static string WrongGyroscopeOrAccelerometer {
            get {
                return ResourceManager.GetString("WrongGyroscopeOrAccelerometer", resourceCulture);
            }
        }
    }
}
